### ISSUE TITLE
working on a similar project, would like to get in touch

### ISSUE THREAD

**Issue by alexandrecuer** [ibpsa/project1-boptest-gym#117]
Sorry if you feel this intrusive but i think we are working on very similar subjects. I tried to understand the boptest approach but not i cannot say i've really understood yet. Seems to be quite complex and i need more time to dive into it. 

Anyway, since 2020 I work on a AI controller based on a nvidia jetson nano to command the heating circuits of tertiary buildings.

This controller completely bypasses all existing physical controllers : it is not acting through the web and is directly installed in boilers rooms. The embedded intelligence has to adapt to a great variety of circuit configurations and is trained through reinforcement learning, mostly via offline-policy methods such as double dqn, on a simplified simulator developped for the occasion :

https://github.com/Open-Building-Management/EnergyGym

The very first prototypes are already deployed on the field. It is quite promising and except from very extreme situations, the first neural network shows a real autoadapt ability.

Would you be interested to get in touch ?

On the github repo, most docs are in french, but i've got an academic summary/presentation of the research that i can quickly traduce . 

Best

Alex

**Comment by JavierArroyoBastida** [comment]
Hey @alexandrecuer, I'm very sorry I somehow missed your issue. It's a long time since I don't work directly on this project and I see it only now that I'm going to make an update. Nice to see you're working on the EnergyGym project, it's also looking quite sophisticated! Please reach me out directly through email if you're still interested in having a chat. My contact details [here](https://www.kuleuven.be/wieiswie/nl/person/00110910).
