### ISSUE TITLE
Confirm compatible with BOPTEST version

### ISSUE THREAD

**Issue by dhblum** [ibpsa/project1-boptest-gym#93]
@JavierArroyoBastida I think it would be good to indicate (readme or otherwise) what version the gym environment has been tested with, and update as needed.  We could start with v0.2.0.

**Comment by JavierArroyoBastida** [comment]
@dhblum I agree with the suggestion. That was my intention when adding the commit of the BOPTEST repo used in the test script itself. See:
https://github.com/ibpsa/project1-boptest-gym/blob/7906edff7c6b7cd521637c110bddd7f26236f3c6/testing/test_boptestGymEnv.py#L5

It's long since I do not maintain this repo, but I expect to implement an important update/refactoring in the coming weeks. 
I'll use this issue to indicate the tested BOPTEST version more formally, e.g. by using official BOPTEST releases and adding that info to the `README`.

**Comment by JavierArroyoBastida** [comment]
Indeed! I'll label the first release of this repository after refactoring.

**Comment by dhblum** [comment]
Thanks @JavierArroyoBastida.  That sounds fine, I think as long as backward (in)compatibility is captured in release notes.
